# Generated by Django 2.0.8 on 2018-11-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='scheduler.Doctor'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
