# Generated by Django 2.0.5 on 2018-06-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
