# Generated by Django 2.0.12 on 2019-02-23 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20181103_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='fired_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hired_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
