# Generated by Django 2.0.8 on 2018-11-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20181103_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
