# Generated by Django 2.0.12 on 2019-02-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20190223_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fired_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hired_date',
            field=models.DateField(null=True),
        ),
    ]
